<?php
/**
 * Created by PhpStorm.
 * User: magobeodo
 * Date: 26/11/18
 * Time: 8:47
 */

class BloqueoDAO extends DAO
{
    protected static $table = "bloqueo";
    protected static $class = "Bloqueo";

    public static function insert($id, $activo, $fechaInicio, $fechaFin)
    {
        // TODO: Implement insert() method.

    }

    public static function getBy($column, $value)
    {
        return parent::getBy($column, $value); // TODO: Change the autogenerated stub
    }

    public static function deleteById($id)
    {
        parent::deleteById($id); // TODO: Change the autogenerated stub
    }
}