<?php
/**
 * Created by PhpStorm.
 * User: magobeodo
 * Date: 26/11/18
 * Time: 8:49
 */

class HabitacionDAO extends DAO
{
    protected static $table = "habitacion";
    protected static $class = "Habitacion";

    public static function insert()
    {
        // TODO: Implement insert() method.
    }

    public static function getBy($column, $value)
    {
        return parent::getBy($column, $value); // TODO: Change the autogenerated stub
    }

    public static function deleteById($id)
    {
        parent::deleteById($id); // TODO: Change the autogenerated stub
    }
}