<?php
/**
 * Created by PhpStorm.
 * User: magobeodo
 * Date: 26/11/18
 * Time: 8:51
 */

class PersonaDAO extends DAO
{
    protected static $table = "persona";
    protected static $class = "Persona";

    public static function insert($nombre, $apellido1, $apellido2, $dni, $tlf, $correo, $password, $fechaN)
    {
        // TODO: Implement insert() method.
        $sql = "INSERT INTO `persona` (`nombre`, `apellido1`, `apellido2`, `DNI`, `tlf`, `correo`, `password`, `fechaNacimiento`)
VALUES (:nombre, :apellido1, :apellido2, :dni, :tlf,:correo,:passw,:fechN)";
        $stmt = DB::conn()->prepare($sql);
        $stmt->bindValue(':nombre', $nombre);
        $stmt->bindValue(':apellido1', $apellido1);
        $stmt->bindValue(':apellido2', $apellido2);
        $stmt->bindValue(':dni', $dni);
        $stmt->bindValue(':tlf', $tlf);
        $stmt->bindValue(':correo', $correo);
        $stmt->bindValue(':passw', $password);
        $stmt->bindValue(':fechaNacimiento', $fechaN);
        $r = $stmt->execute();
        if ($r) {
            echo 'Te has Registrado Correctamente';
        } else {
            echo 'Ha habido un error en el proceso de registro';
        }

    }

    public static function getBy($column, $value)
    {
        return parent::getBy($column, $value); // TODO: Change the autogenerated stub
    }

    public static function getByCorreo($correo)
    {
        $res = parent::getBy("correo", $correo);
        if (isset($res))
            return $res[0];
        return null;
    }
}